# Generated by Django 2.0 on 2018-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(db_index=True, max_length=20, verbose_name='身份证号码')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='姓名')),
                ('nick_name', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='别名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('dob', models.DateTimeField(verbose_name='出生日期')),
                ('telephone', models.CharField(db_index=True, max_length=20, verbose_name='电话号码')),
            ],
        ),
    ]
