# Generated by Django 2.0 on 2018-07-01 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='regist_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间'),
        ),
    ]
