# Generated by Django 2.0 on 2018-11-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_regist_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '会员卡',
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '患者信息', 'verbose_name_plural': '患者信息'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='regist_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='card',
            name='ower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
